### Leitura dos microdados 2019 - Data de atualização: 15/09/2020:

In [2]:
import pandas as pd

df_2019 = pd.read_csv('../microdados_matriculas_2019.csv', sep=';')

df_2019.head()

,Teste,Carga Horaria,Carga Horaria Minima,Categoria da Situação,Código do Ciclo Matricula,Código da Matricula,Código da Unidade de Ensino - SISTEC,Cod Unidade,Cor / Raça,Data de Inicio do Ciclo,...,Vagas Extraordinárias l9,Vagas Regulares AC,Vagas Regulares l10,Vagas Regulares l13,Vagas Regulares l14,Vagas Regulares l1,Vagas Regulares l2,Vagas Regulares l5,Vagas Regulares l6,Vagas Regulares l9
0,1,4535,3600,Concluintes,1978481,64063592,3483,147,Não declarada,20/02/2015,...,0.0,17.0,0.0,0.0,0.0,2.0,7.0,2.0,7.0,0.0
1,1,4535,3600,Em curso,1978481,64063608,3483,147,Não declarada,20/02/2015,...,0.0,17.0,0.0,0.0,0.0,2.0,7.0,2.0,7.0,0.0
2,1,4535,3600,Em curso,1978481,64063640,3483,147,Não declarada,20/02/2015,...,0.0,17.0,0.0,0.0,0.0,2.0,7.0,2.0,7.0,0.0
3,1,4535,3600,Em curso,1978481,64063638,3483,147,Não declarada,20/02/2015,...,0.0,17.0,0.0,0.0,0.0,2.0,7.0,2.0,7.0,0.0
4,1,4535,3600,Em curso,1978481,64063630,3483,147,Não declarada,20/02/2015,...,0.0,17.0,0.0,0.0,0.0,2.0,7.0,2.0,7.0,0.0

### Verificando nome das colunas:

In [3]:
df_2019.columns.tolist()

['Teste',
 'Carga Horaria',
 'Carga Horaria Minima',
 'Categoria da Situação',
 'Código do Ciclo Matricula',
 'Código da Matricula',
 'Código da Unidade de Ensino - SISTEC',
 'Cod Unidade',
 'Cor / Raça',
 'Data de Inicio do Ciclo',
 'Data de Fim Previsto do Ciclo',
 'Data de Ocorrencia da Matricula',
 'Eixo Tecnológico',
 'Faixa Etária',
 'Fator Esforco Curso',
 'Fonte de Financiamento',
 'Idade',
 'Total de Inscritos',
 'Instituição',
 'Mês De Ocorrência da Situação',
 'Modalidade de Ensino',
 'Código do Município com DV',
 'Município ',
 'Vagas Ofertadas',
 'Nome de Curso',
 'Número de registros',
 'Região ',
 'Renda Familiar',
 'Sexo',
 'Situação de Matrícula',
 'Sub Eixo Tecnologico',
 'Tipo Oferta',
 'Tipo de Curso',
 'Turno',
 'UF ',
 'Unidade de Ensino',
 'Vagas Extraordinárias AC',
 'Vagas Extraordinárias l10',
 'Vagas Extraordinárias l13',
 'Vagas Extraordinárias l14',
 'Vagas Extraordinárias l1',
 'Vagas Extraordinárias l2',
 'Vagas Extraordinárias l5',
 'Vagas Extraordinárias l6',
 'Vagas Extraordinárias l9',
 'Vagas Regulares AC',
 'Vagas Regulares l10',
 'Vagas Regulares l13',
 'Vagas Regulares l14',
 'Vagas Regulares l1',
 'Vagas Regulares l2',
 'Vagas Regulares l5',
 'Vagas Regulares l6',
 'Vagas Regulares l9']

### Verificando quantidade total de matrículas 2019:

In [4]:
df_2019['dt_ocorrencia_matricula'] = pd.to_datetime(df_2019['Data de Ocorrencia da Matricula'], format='%d/%m/%Y')
df_2019['ano_ocorrencia_matricula'] = df_2019['dt_ocorrencia_matricula'].dt.year
df_2019['dt_fim_ciclo'] = pd.to_datetime(df_2019['Data de Fim Previsto do Ciclo'], format='%d/%m/%Y')
df_2019['ano_fim_ciclo'] = df_2019['dt_fim_ciclo'].dt.year

df_2019_qtd_matriculas = df_2019[(df_2019['Instituição'] == 'IFSUL')]
df_2019_qtd_matriculas.shape

(21939, 58)

### Filtrando matrículas por tipo de oferta Integrado e Proeja Integrado:

In [5]:
import numpy as np
import statistics

f_integrado = df_2019_qtd_matriculas[(df_2019_qtd_matriculas['Tipo Oferta'] == 'Integrado')]
qtd_matriculas_integrado = f_integrado.groupby(['Tipo Oferta', 'Situação de Matrícula'])['Tipo Oferta'].count().sum()

f_proeja = df_2019_qtd_matriculas[(df_2019_qtd_matriculas['Tipo Oferta'] == 'PROEJA - Integrado')]
qtd_matriculas_proeja = f_proeja.groupby(['Tipo Oferta', 'Situação de Matrícula'])['Tipo Oferta'].count().sum() 

lista_qtd_matriculas_cti_eja_2019 = [qtd_matriculas_integrado,qtd_matriculas_proeja]

lista_qtd_matriculas_cti_eja_2019

[7350, 693]

### Salvando informações em arquivo csv

In [6]:
a = np.asarray(lista_qtd_matriculas_cti_eja_2019)
a.tofile('tmp_files/matriculados-cti-eja-2019.csv', sep=',')